### ISSUE TITLE
Support for FROM scratch containers

### ISSUE THREAD

**Issue by jdoss** [ansible-community/ansible-bender#128]
I am looking to convert the following bash script over to an ansible playbook to use with ansible-bender. After digging a bit, I don't think there is any support for creating containers from scratch. Is that correct? 

I have been calling this script with `buldah unshare`. My end goal is to write one playbook to support many different distros and versions and pass in extra_ vars to dictate what is built from scratch. 

```
#!/usr/bin/env bash
set -o errexit

FEDORA_VERSION=29
CONTAINER=$(buildah from scratch)

MOUNTPOINT=$(buildah mount ${CONTAINER})

dnf install --disablerepo=* --enablerepo=fedora,updates \
            --installroot ${MOUNTPOINT} \
            --releasever ${FEDORA_VERSION} \
              glibc-minimal-langpack bash coreutils dnf procps-ng vi \
            --nodocs \
            --setopt install_weak_deps=false -y
dnf -y clean all --installroot=${MOUNTPOINT}

buildah config --author joe@example.biz \
               --user 1001 ${CONTAINER}

buildah commit ${CONTAINER} localhost/fedora:${FEDORA_VERSION}

buildah unmount ${CONTAINER}
buildah rm ${CONTAINER}```

**Comment by TomasTomecek** [comment]
We are already tracking a very similar feature request over here: https://github.com/ansible-community/ansible-bender/issues/49

**Comment by jdoss** [comment]
Thanks @TomasTomecek for your response. I'll close this issue in favor of #49.
