### ISSUE TITLE
Need a way to add things to generated ansible.cfg

### ISSUE THREAD

**Issue by jordemort** [ansible-community/ansible-bender#141]
I am adding a buildah transport to Mitogen in https://github.com/dw/mitogen/pull/595 - with this, and a suitably hacked `ansible-bender`, I've gotten my container build time down from 12 minutes to 5 minutes. Usually, when you want to use Mitogen with Ansible, you add something like this to your `ansible.cfg`:

```
[defaults]
strategy_plugins = /path/to/mitogen-0.2.7/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
```

`ansible-bender` generates an `ansible.cfg` on the fly, so I needed to hack my copy to include those lines. But of course not everyone will want to use Mitogen and not everyone who does will have it installed in the same place. I am able to get away without the `strategy` line by injecting `ANSIBLE_STRATEGY=mitogen_linear` into the environment, but without the `strategy_plugins` line, Ansible is unable to find the plugin. What do you think the best way to extend `ansible-bender` in order to support this would be?

**Comment by jordemort** [comment]
Just figured out I can set `ANSIBLE_STRATEGY_PLUGINS` in the environment too, looks like I'm covered here.

**Comment by TomasTomecek** [comment]
This is still worth documenting, though.
