### ISSUE TITLE
Provide version status parameter

### ISSUE THREAD

**Issue by kr4ut** [ansible-community/ansible-bender#143]
Appreciating all new releases of ansible-bender a `--version` parameter would be nice!
A rather low hanging fruit and at best analog to `ansible --version` should do the trick.
The current approach going via pip and grep for the module name feels a bit hacky:
```
[ansible@buildah ~]$ pip3 freeze | grep ansible-bender
You are using pip version 8.1.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ansible-bender==0.7.0
```
Hope this also creates more version awareness in the user feedback to the project.
Providing some additional information like with `ansible --version` would be a plus:
```
[ansible@buildah ~]$ ansible --version
ansible 2.8.1
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
BTW big thanks for pushing this important bridge for cfgmgmt into the container world :1st_place_medal:
@TomasTomecek Appreciate to invite you for fancy dinner somewhere at FOSDEM/CfgMgmtCamp :+1:

**Comment by TomasTomecek** [comment]
This is a very nice suggestion!

> BTW big thanks for pushing this important bridge for cfgmgmt into the container world :1st_place_medal:

You're welcome!

> @TomasTomecek Appreciate to invite you for fancy dinner somewhere at FOSDEM/CfgMgmtCamp +1

:D No worries, I'm glad you find this project useful.

I hope to get to fosdem 2020, finally, never managed to get to fosdem.
