### ISSUE TITLE
Required python version?

### ISSUE THREAD

**Issue by noudAndi** [ansible-community/ansible-bender#146]
Hey,

I struggled a lot, getting this tool running. A major problem is having the right python version. There is no hint in the docs, that 3.7 or 3.6 are required.

I guessed it by reading ticket https://github.com/ansible-community/ansible-bender/issues/63 Please at least add this information to readme.

On the other hand, pls consider supporting lower python versions, most distributions don't contain those versions yet.

Ubuntu 16.04 fails to run ansible-bender, because of python 3.5 :( (see below)

```
root@ubuntu-xenial:~# ansible-bender
Traceback (most recent call last):
  File "/usr/local/bin/ansible-bender", line 7, in <module>
    from ansible_bender.cli import main
  File "/usr/local/lib/python3.5/dist-packages/ansible_bender/cli.py", line 12, in <module>
    from ansible_bender.api import Application
  File "/usr/local/lib/python3.5/dist-packages/ansible_bender/api.py", line 7, in <module>
    from ansible_bender.builder import get_builder
  File "/usr/local/lib/python3.5/dist-packages/ansible_bender/builder.py", line 6, in <module>
    from ansible_bender.builders.buildah_builder import BuildahBuilder
  File "/usr/local/lib/python3.5/dist-packages/ansible_bender/builders/buildah_builder.py", line 305
    raise RuntimeError(f"no python interpreter was found in the base image \"{self.build.base_image}\""
                                                                                                      ^
SyntaxError: invalid syntax
```

**Comment by TomasTomecek** [comment]
That's a good point, I should be specific about the minimal version of python 3.

As the readme states:
```
# Requirements
* Ansible
  * Ansible needs to be built against python 3
* Python 3

Last two requirements can be pretty tough: you can always run bender in a privileged container.
```

**Comment by TomasTomecek** [comment]
> On the other hand, pls consider supporting lower python versions, most distributions don't contain those versions yet.
> 
> Ubuntu 16.04 fails to run ansible-bender, because of python 3.5 :( (see below)

If you look at the commit history, you can see this project is pretty much a one-man-show (and a community project with no official support). Sadly I have almost no free time lately so I don't have resources nor motivation (to be honest) to add support for python 3.5

**Comment by noudAndi** [comment]
Sorry for ressurecting this issue, but which Distribution are you using? Cannot find one containing python >= 3.6 and buildah executables running out of the box.

Maybe Fedora?

**Comment by TomasTomecek** [comment]
@noudAndi yup, Fedora 30 https://github.com/ansible-community/ansible-bender/blob/master/Vagrantfile#L12

I'm also testing bender on gentoo from time to time. Feel free to open issues if you run into problems or even have questions.

**Comment by TomasTomecek** [comment]
This is how you can run bender in a privileged container https://github.com/ansible-community/ansible-bender/blob/master/Makefile#L18 (so your distro can be pretty much anything which is able to run podman or docker)
