### ISSUE TITLE
[question] running ansible-bender inside unprivileged containers

### ISSUE THREAD

**Issue by miquecg** [ansible-community/ansible-bender#151]
I'm trying to use ansible-bender inside an unprivileged container run by systemd-nspawn. This runtime by default limits access to some host capabilites:

> systemd-nspawn limits access to various kernel interfaces in the container to read-only, such as /sys, /proc/sys or /sys/fs/selinux. Network interfaces and the system clock may not be changed from within the container. Device nodes may not be created.
>
> https://wiki.archlinux.org/index.php/Systemd-nspawn

So basically I'm having problems with all podman commands called by ab so far. For instance the [simple-playbook](https://github.com/ansible-community/ansible-bender/blob/master/simple-playbook.yaml) fails when podman tries to run the base image:

```
[root@root ~]# podman run --rm python:3-alpine
ERRO[0002] unable to remove container d902bcf5a5840c56242e86c0632f399616c739ba674668b8cf66c6b953fbbf04 after failing to start and attach to it 
Error: container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/machine.slice: read-only file system\""
: OCI runtime error
```

As a solution, systemd-nspawn allows to run containers adding extra capabilities:

```
➜  $ systemd-nspawn --capability=CAP_
CAP_CHOWN             CAP_KILL              CAP_SETFCAP           CAP_SYS_CHROOT      
CAP_DAC_OVERRIDE      CAP_LEASE             CAP_SETGID            CAP_SYS_NICE        
CAP_DAC_READ_SEARCH   CAP_LINUX_IMMUTABLE   CAP_SETPCAP           CAP_SYS_PTRACE      
CAP_FOWNER            CAP_NET_BIND_SERVICE  CAP_SETUID            CAP_SYS_RESOURCE    
CAP_FSETID            CAP_NET_BROADCAST     CAP_SYS_ADMIN         CAP_SYS_TTY_CONFIG  
CAP_IPC_OWNER         CAP_NET_RAW           CAP_SYS_BOOT 
```

Ideally I should pick the one with least privileges that allows podman to run. Which one it is? I'm a bit worried about `CAP_SYS_ADMIN` (full host access) just in case it messes up some config or setup on the host side (e.g. residual files).

Thanks and feel free to close if this is too much off-topic here. I've decided to ask because some others trying ab for the first time can have also these same doubts, specially when you are not very familiar with all the implications about containers.

**Comment by TomasTomecek** [comment]
You might get better answers if you ask at podman/buildah issue tracker.

@TomSweeneyRedHat actually blogged about running buildah in a podman container: https://developers.redhat.com/blog/2019/04/04/build-and-run-buildah-inside-a-podman-container/

**Comment by miquecg** [comment]
Thanks for the info. Closing for now.
