### ISSUE TITLE
Add __main__.py

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#16]
P.P.S. Please add `__main__.py` to allow `python3 -m ansible_bender`, which makes interpreter selection explicit ;)

_Originally posted by @webknjaz in https://github.com/TomasTomecek/ansible-bender/issues/11#issuecomment-436759783_

**Comment by kmehant** [comment]
@TomasTomecek I would like to work on this issue.

**Comment by kmehant** [comment]
Shall we close this.

**Comment by webknjaz** [comment]
@kmehant FYI GitHub supports closing keywords. If you'd used, `Resolves #16` in your PR description, merging it would close this too.
Doc: https://help.github.com/en/articles/closing-issues-using-keywords.

**Comment by TomasTomecek** [comment]
oh right, haven't noticed it's still up
