### ISSUE TITLE
Centos:8 container does not provide python in know locations (only plattform-python)

### ISSUE THREAD

**Issue by hhenkel** [ansible-community/ansible-bender#170]
As RHEL 8 / Centos 8 by default "only" provide python via packages like "platform-python-3.6.8-1.el8.0.1.x86_64" this results in problems with the ```docker.io/library/centos:8``` container and ansible bender. 

```
$ ansible-bender build main.yml
12:03:07.483 buildah_builder.py ERROR  couldn't locate python interpreter, tried these paths: ('/usr/bin/python3', '/usr/local/bin/python3', '/usr/bin/python3.7', '/usr/bin/python37', '/usr/bin/python3.6', '/usr/bin/python36', '/usr/bin/python2', '/usr/local/bin/python2', '/usr/bin/python', '/usr/local/bin/python')
There was an error during execution: no python interpreter was found in the base image "docker.io/library/centos:8", you can specify the path via CLI option --python-interpreter
```

The mentioned workaround with ```--python-interpreter /usr/libexec/platform-python``` works fine, but it is propably a good idea to add the location to the search list. I will do a according PR for that.

**Comment by TomasTomecek** [comment]
Thanks for such a quick fix!
