### ISSUE TITLE
Add available subcommands with descriptions to --help option 

### ISSUE THREAD

**Issue by kmehant** [ansible-community/ansible-bender#200]
We have flags with usage mentioned in ansible-bender while using the `--help` option, but such a thing is missing for subcommands, shall we have that covered too?

**Comment by kmehant** [comment]
@TomasTomecek Please let me know your thoughts regarding this.

**Comment by TomasTomecek** [comment]
Sounds good (if you know how to do that with argparse).

**Comment by kmehant** [comment]
> Sounds good (if you know how to do that with argparse).

If I am not wrong, I guess we just need to add help tags to all commands. Presently they just have decription tags.
