### ISSUE TITLE
Latest build-id will now no longer be next_build_id - 1

### ISSUE THREAD

**Issue by kmehant** [ansible-community/ansible-bender#204]
As now we have introduced `clean` subcommand to ansible-bender, there is possibility of cleaning any build due to the unavailability of the corresponding image on disk.
What I later found was clean subcommand breaks the previous design of returning the latest `build-id` as `next_build_id - 1`.  
We need to find a better way to return the latest build-id which would be the highest `build-id `from the available ones. 

I got to understand this when trying `get-logs` subcommand. #201

**Comment by kmehant** [comment]
@TomasTomecek Shall we return the last key in the dictionary instead?

**Comment by TomasTomecek** [comment]
Wow, this is a very interesting problem.

To be honest, I wouldn't return anything: I'd just inform user that latest build is no longer available (and that it was cleaned probably) and that they need to specify which build they need.

**Comment by kmehant** [comment]
@TomasTomecek presently ab informs as `There is no such build with ID $` for both cases
* invalid build-id 
* latest build-id (which is not there becomes invalid)
What are your thoughts regarding this? Shall we continue with this without any changes?

**Comment by TomasTomecek** [comment]
@kmehant we can polish the error message and provide more info if you feel like that would be more helpful to the users
