### ISSUE TITLE
Documentation about known variables

### ISSUE THREAD

**Issue by bmillemathias-1a** [ansible-community/ansible-bender#211]
Hello,

I was fiddling with `ab` to find how to create a playbook to build a container and failed to find the known variables bender use (I have a vague idea looking at the example in the `README` file though.

Is it possible to add them, or at least provide it here and I'll do a PR to add them to the `README` file.

Thanks

**Comment by kmehant** [comment]
@bmillemathias-1a  Hi, I would like you to look in to this document [ab configuration](https://github.com/ansible-community/ansible-bender/blob/master/docs/configuration.md). Hopefully it helps you. 
May be we should add a link to this doc in the README.md for better visibility, @TomasTomecek please let us know your thoughts regarding this.

**Comment by bmillemathias-1a** [comment]
> @bmillemathias-1a Hi, I would like you to look in to this document [ab configuration](https://github.com/ansible-community/ansible-bender/blob/master/docs/configuration.md). Hopefully it helps you.

oups, sorry for the noise.

As you said a simple link from README to this file would be great.
I can provide the PR.

**Comment by kmehant** [comment]
> > @bmillemathias-1a Hi, I would like you to look in to this document [ab configuration](https://github.com/ansible-community/ansible-bender/blob/master/docs/configuration.md). Hopefully it helps you.
> 
> oups, sorry for the noise.
> 
> As you said a simple link from README to this file would be great.
> I can provide the PR.

Sure thank you.
