### ISSUE TITLE
Terminal character buffer messed up after ansible-bender build on ubuntu 18.04

### ISSUE THREAD

**Issue by gitttt** [ansible-community/ansible-bender#218]
Steps to reproduce:

- Open a new shell
- `vagrant@ubuntu1804:~/ansible_bender_experiments$ source venv/bin/activate`
- `(venv) vagrant@ubuntu1804:~/ansible_bender_experiments$ ansible-bender build playbook.yml`
- `(venv) vagrant@ubuntu1804:~/ansible_bender_experiments$ podman run -it d0fd5e958f61 sh`
- terminal in container is blocked
- From other terminal: `killall -9 podman`
- First terminal shows
   `# (venv) vagrant@ubuntu1804:~/ansible_bender_experiments$ ;5R`
- Terminal character buffer is messed up, seems that every command is prepended by some strange chars

**Workaround:**
-  Open a new bash inside the current one and exit it
- `# (venv) vagrant@ubuntu1804:~/ansible_bender_experiments$ bash`
- `# vagrant@ubuntu1804:~/ansible_bender_experiments$ exit`
- `# exit`
- `# (venv) vagrant@ubuntu1804:~/ansible_bender_experiments$ podman run -it d0fd5e958f61 sh`
- Now it works

**Comment by TomasTomecek** [comment]
Usually when my terminal gets messed up, I run `reset` which cleans things up.

**Comment by TomasTomecek** [comment]
Anyway, thank you for opening the issue but this is a clearly an issue with podman, not ab. There is literally nothing we can do on bender's side to resolve this - running the container with podman changes the terminal behaviour, as you describe it.

Hence I'm closing, I suggest opening this at https://github.com/containers/libpod
