### ISSUE TITLE
Alternative: Create Image with Molecule Docker Driver + `docker commit`

### ISSUE THREAD

**Issue by hswong3i** [ansible-community/ansible-bender#220]
I would like to propose an alternative solution for Ansible-based Docker image creation, by using Molecule Docker driver + `docker commit`.

The key benefit include:
- No `buildah` or `podman` required (anyway, both docker-based or podman-based are supported by Molecule's drivers), therefore [Travis CI friendly](https://github.com/alvistack/docker-sshd/blob/master/.travis.yml)
- Simply define meta data or initial patches with `RUN` into `Dockerfile.j2` 
- All standard Ansible features are supported (e.g. `include_playbook`, `include_role`, `group_vars`, etc) during core provision phase
- Simple debug with `docker exec` into running container, as standard Molecule-based debug workflow

# Create a standard Ansible Role
```
molecule init role -d docker dummy
```

# Create `molecule/default/create.yml`
Here the key points are:
- If `molecule/default/Dockerfile.j2` provided then build a temporary docker image with unique name `role_name/scenario_name:instance_name`
- Else if `image: ubuntu-18.04` provided in `molecule.yml` then just re-tag it with unique name `role_name/scenario_name:instance_name`

Such `role_name/scenario_name:instance_name` will therefore being reused in verify phase, in order to figure our original base image's `ENTRYPOINT` and `CMD`

E.g. download my [create.yml](https://github.com/alvistack/docker-sshd/blob/master/molecule/default/create.yml) which patched with above logic.

# Prepare `molecule/default/Dockerfile.j2`
Here the key points are:
- Define the result image's `ENTRYPOINT` and `CMD` here (which will be overwrite during initial provision phase by Molecule with `/bin/sh -c bash -c "sleep infinity"`)
- Define other else meta data for the result image
- As simple as possible initial patch with `RUN`, e.g. enable systemd support for `ubuntu:18.04`

E.g. my example for [Ubuntu 18.04 + systemd support](https://github.com/alvistack/docker-sshd/blob/master/molecule/7.6/Dockerfile.j2).

# Implement `molecule/default/converge.yml`
E.g. my core logic for install [sshd with Ansible role](https://github.com/alvistack/docker-sshd/blob/master/playbooks/converge.yml)

# Create `molecule/default/verify.yml`
Here the key points are:
- Cleanup build caches, e.g. APT/RPM package cache
- Fetch original base image's `ENTRYPOINT` and `CMD`
- `docker commit` the result running container as new image, with fetched original base image's `ENTRYPOINT` and `CMD`, named `role_name/scenario_name:instance_name-commit`

E.g. download my [verify.yml](https://github.com/alvistack/docker-sshd/blob/master/molecule/default/verify.yml) which patched with above logic.

# Run with `molecule test -s default`
Once completed you could re-tag the result image from `role_name/scenario_name:instance_name-commit` into your new name, e.g. my `alvistack/sshd:7.6`

**Comment by TomasTomecek** [comment]
Hey, thanks for taking time to write this down so thoroughly.

I'm not sure I understand the point of this issue - what is the action item to do in this repository?

**Comment by hswong3i** [comment]
@TomasTomecek what if we add some documentation for compare different methods PROS and CONS? e.g.
  - By Dockerfile, with raw shell scripting
  - By Dockerfile, install Python and Ansible, copy playbook into container, run playbook via localhost inside container
  - By ansible-bender, everything basically goes into single playbook file
  - By Ansible + Molecule Docker driver + docker commit

**Comment by TomasTomecek** [comment]
Yup, documentation sounds like a good idea - I'd suggest add it to molecule though - we're in a process of establishing documentation here so it would take some time to publish such documentation in bender's docs.

**Comment by hswong3i** [comment]
Now I just use packer for docker build, much simple ;-)
