### ISSUE TITLE
installation instructions should mention dependency on crun 

### ISSUE THREAD

**Issue by tpo** [ansible-community/ansible-bender#264]
Instead of making a pull request that would fix this I just describe the problem here, since I am not sure how things are on other distros than Debian.

The problem:
```
$ ansible-bender build ./simple-playbook.yaml 
12:52:40.734 utils.py          ERROR  error running container: error creating container for [/bin/true]: : exec: "crun": executable file not found in $PATH
12:52:40.738 utils.py          ERROR  error while running runtime: exit status 1
12:52:40.739 utils.py          ERROR  level=error msg="exit status 1"
12:52:40.740 buildah_builder.py ERROR  Unable to create or run a container using docker.io/python:3-alpine with buildah
error running container: error creating container for [/bin/true]: : exec: "crun": executable file not found in $PATH
error while running runtime: exit status 1
level=error msg="exit status 1"
There was an error during execution: Command '['buildah', 'run', 'a-very-nice-image-20211228-125236421634-cont-20211228125236499354', 'true']' returned non-zero exit status 1.
```
This is a Debian stable ("bullseye") system.

The solution:
```
$ sudo apt install crun
```
Should the `crun` dependency be mentioned in the docu [here](https://ansible-community.github.io/ansible-bender/build/html/installation.html#requirements-host)?

**Comment by TomasTomecek** [comment]
This sounds like a packaging mistake in Debian packaging: I'd say that installing buildah should install crun as well.

On the other hand, I don't see any harm in mentioning this in the readme.

So I'm closing this issue and will accept your PR.
