### ISSUE TITLE
setuptools_scm_git_archive now included in setuptools_scm >=7.0.0

### ISSUE THREAD

**Issue by grawlinson** [ansible-community/ansible-bender#280]
Hi! Arch Linux packager here, we've discovered that functionality provided by `setuptools_scm_git_archive` is now included in `setuptools_scm`.

Upstream has updated their [documentation](https://github.com/Changaco/setuptools_scm_git_archive/) with a migration guide also.

**Comment by TomasTomecek** [comment]
Thank you for the headsup! This seems like a trivial fix, let me do that.
