### ISSUE TITLE
automate releasing

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#291]
* [x] copy-pasta https://github.com/packit/ogr/blob/main/.github/workflows/pypi-publish.yml **reuse as much as possible**
* [x] document how to use this
* [x] ~~create a new PyPI user~~ using the trusted publishing (read below)
  * [x] ~~grant it maintainer perms on https://pypi.org/manage/project/ansible-bender/~~
  * [x] ~~save password here in github secrets~~
  * [x] ~~this user will only be used in the automation!~~

**Comment by grawlinson** [comment]
PyPA have a [guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) for automated releases and I've been looking at it for some projects recently.

**Comment by TomasTomecek** [comment]
oh sweet, thanks for the pointer!

**Comment by webknjaz** [comment]
> PyPA have a [guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) for automated releases and I've been looking at it for some projects recently.

Note that it needs updating, I haven't had time to look into that, sadly.

**Comment by webknjaz** [comment]
> * [ ]  create a new PyPI user
>   
>   * [ ]  grant it maintainer perms on https://pypi.org/manage/project/ansible-bender/
>   * [ ]  save password here in github secrets
>   * [ ]  this user will only be used in the automation!

@TomasTomecek may I invite you into the private beta of _secretless_ OIDC-based publishing from GHA to PyPI? Please, fill out https://forms.gle/XUsRT8KTKy66TuUp7 to get access/feature flag on + see the instructions. My `pypi-publish` action supports this mode already. You can either create a bot account as in the checklist, or use your own. FWIW you can fill out the form for multiple accounts too, so enroll both.

> [ ] copy-pasta https://github.com/packit/ogr/blob/main/.github/workflows/pypi-publish.yml

As you enroll, you'll get access to a better instruction on this in a private repo. Although, I can contribute it right away, if needed.

**Comment by webknjaz** [comment]
@TomasTomecek it's GA now: https://twitter.com/webknjaz/status/1649166562673426433
