### ISSUE TITLE
use atomic way of acquiring database lock

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#47]
https://github.com/TomasTomecek/ansible-bender/blob/b89454ae514073e456d2d44bfe1f4415440c2d81/ansible_bender/db.py#L94

Right now it's `open(..., "r")` and `open(..., "w")`. That's not atomic -- there is a race condition. We should add an atomic way of acquiring the lock.

**Comment by kmehant** [comment]
@TomasTomecek Shall we lock the lock file using [filelock](https://pypi.org/project/filelock/) module so our read and write operations become atomic. Please let me know your thoughts regarding this 😄

**Comment by TomasTomecek** [comment]
I don't think we actually need a dedicated library for such a thing. It should be enough to utilize `open` for this:
```
$ man 3 open
...
       O_EXCL        If  O_CREAT  and  O_EXCL  are set, open() shall fail if the file exists. The check for the existence of the file and the creation of the file if it
                     does not exist shall be atomic with respect to other threads executing open() naming the same filename  in  the  same  directory  with  O_EXCL  and
                     O_CREAT set. If O_EXCL and O_CREAT are set, and path names a symbolic link, open() shall fail and set errno to [EEXIST], regardless of the contents
                     of the symbolic link. If O_EXCL is set and O_CREAT is not set, the result is undefined.
```

https://stackoverflow.com/a/5211172/909579

**Comment by kmehant** [comment]
@TomasTomecek  Those seem better options to add, Shall I send a PR for the same

**Comment by TomasTomecek** [comment]
@kmehant yes, PR is very welcome: let me know if I can assist you in any way

One thing: the CI is not functional at the moment so you need to run all the tests locally on your laptop.

**Comment by kmehant** [comment]
@TomasTomecek Please review my changes
* Make read and write operations atomic: https://github.com/kmehant/ansible-bender/commit/6df05242ee87b870277e4e9274ad5bf3eb6d44ab 
* Update gitignore:  https://github.com/kmehant/ansible-bender/commit/6256eab76e1433306c433e21e0ea4939e4df532e 

Could you please guide me with any developer docs so that I can set up my environment properly for testing. Thank you.

**Comment by TomasTomecek** [comment]
@kmehant could you please open a pull request? that's easier to review

I'm gonna write some dev docs right now.
