### ISSUE TITLE
disable possibility of changing users when running in rootless mode

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#48]
When running as rootless container, it appears that you are root in the container but in fact you are not. Changing the container user to an unprivileged one doesn't make sense and even can't work. Let's disable changing user when running as rootless, produce an error when such thing happens and point to some docs.

**Comment by kmehant** [comment]
@TomasTomecek can I know more information regarding this. 
Is that something like if the user runs ansible bender in rootless mode, then the user will be restricted in giving a UID (through playbook using `user` key) to configure Buildah for user in buildah container?

**Comment by TomasTomecek** [comment]
> Is that something like if the user runs ansible bender in rootless mode, then the user will be restricted in giving a UID (through playbook using `user` key) to configure Buildah for user in buildah container?

Mehant, exactly this. When you are an unprivileged user, the linux security model makes it hard to change UID (without doing a login). User namespaces make this even more complicated because you are getting weird errors which are hard to understand.

Feel free to try this out by creating a playbook which does some basic operations like creating or reading files, running commands etc. and then run it rootless: once with uid 0 and then pick some other uid.
